### ISSUE TITLE
.gitignore ignored one of my heade files.

### ISSUE THREAD

**Issue by Kaaserne** [bojanpotocnik/nRF5-SDK#2]
https://github.com/bojanpotocnik/nRF5-SDK/blob/79e3e0a4c4a83d8087a273b52c88b451f0cba185/.gitignore#L18

I don't know where you got the `.gitignore` from, anyways, I'm here just to tell that this line caused that a certain `.h` file of my own project, got ignored. My file was called `SystemSyatusses.h`. Obviously the `ses.h` part did it.

**Comment by bojanpotocnik** [comment]
Thank you for this information.

To be honest, I forgot about this repo as I later moved to a different method of including the nRF SDK, described [here](https://github.com/bojanpotocnik/nrf52_ble_app_template#prerequisite). This way I only have one, unmodified instance of the original SDK downloaded to some location on the disk and used by all projects (using this version of the SDK). I think this is the easiest and also the most correct way of doing this (after all, the SDK shall not be modified to avoid headaches). Thank you for reminding me, I will archive this repo tomorrow.

**Comment by Kaaserne** [comment]
Hi no problem. It looks good but in my case it was just easier to add the nRF SDK dependencies as a submodule in another repository. Anyway, thanks for the help. The issue can be closed.
